object Versions {
    const val android = "1.6.21"
    const val kotlin = "1.6.21"
    const val coreKtx = "1.8.0"
    const val timber = "4.7.1"
    const val appCompat = "1.4.2"
    const val material = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val extJunit = "1.1.3"
    const val espressoCore = "3.4.0"
    const val fragmentKtx = "1.5.0-rc01"
    const val viewModel = "2.4.1"
    const val liveData = "2.4.1"
    const val coil = "1.4.0"
    const val okhttp3 = "4.9.1"
    const val retrofit = "2.9.0"
    const val moshi = "1.10.0"
    const val coroutines = "1.6.1"
    const val retrofitCoroutinesAdapter = "0.9.2"
    const val hilt = "2.38.1"
    const val gson = "2.9.0"
    const val support = "1.0.0"
    const val navComponent = "2.4.2"
}